### ISSUE TITLE
建议加入webUI入口

### ISSUE THREAD

**Issue by BlingCc233** [NapNeko/NapCat-Mac-Installer#1]
现版本napcat配置文件和以前的格式有区别，仅方便从webui配置。

**Comment by hguandl** [comment]
安装器获取不到 NapCat 实际运行的信息，运行的时候应该会在日志中打印出 webui 的地址。

<img width="855" alt="image" src="https://github.com/user-attachments/assets/fcf18f50-0658-4bee-bdec-defbde0b4243">

**Comment by BlingCc233** [comment]
是否可以加入通过本地请求得到token，从而生成webui地址

**Comment by hguandl** [comment]
[v1.2](https://github.com/NapNeko/NapCat-Mac-Installer/releases/tag/v1.2) 已添加。
